fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
    concat:
      repo: "puppetlabs/concat"
    apt:
      repo: "puppetlabs/apt"
    epel:
      repo: "puppet/epel"
  repositories:
    wget:
      repo: 'https://github.com/rehanone/puppet-wget.git'
      ref: '1.5.1'
  symlinks:
    deluge: "#{source_dir}"
